---
- name: Restart the Prometheus service
  service:
    name: prometheus
    state: restarted
  listen: restart_prometheus

- name: Reload systemd
  command: systemctl daemon-reload
  listen: systemd_reload

- name: Reload firewalld service
  service:
    name: firewalld
    state: reloaded
    enabled: yes
  listen: reload_firewalld
